version: '3.8'
services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_DATABASE: 'trello_clone'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./data:/var/lib/mysql
